#!/usr/bin/env bash

cd bundle
hub clone ctrlpvim/ctrlp.vim
hub clone flazz/vim-colorschemes
hub clone junegunn/fzf.vim
hub clone mileszs/ack.vim
hub clone othree/html5.vim

if [ -d  vim-javascript ]; then
  echo "Removing pangloss/vim-javascript in favor of yuezk/vim-js"
  rm -rf vim-javascript
fi

hub clone scrooloose/nerdtree
hub clone tpope/vim-commentary
hub clone tpope/vim-rails
hub clone tpope/vim-sensible
hub clone tpope/vim-dadbod
hub clone tpope/vim-fugitive
hub clone prettier/vim-prettier
hub clone MaxMEllon/vim-jsx-pretty
hub clone yuezk/vim-js
